### ISSUE TITLE
[FEATURE] Import seed phrase

### ISSUE THREAD

**Issue by theLockesmith** [retrnull/garnet#7]
**Is your feature request related to a problem? Please describe.**
I'd love the ability to import a Monero seed.

**Describe the solution you'd like**
Within the Monero settings, the ability to import a seed or generate a new seed.

**Bounty (in Bitcoin sats) offered for the implementation**
Incentivize developers to work on your feature. Describe clear milestones to claim payment. 

**Additional context**
Add any other context, video, or screenshots about the feature request here.

**Comment by mister-monster** [comment]
An issue with this is that the seed key in Garnet is derived from your nsec. Allowing imports of seeds would mean that the identity and the wallet would not be connected to each other. This is not a problem as long as the user understands that their nsec will not give them access to their Monero if they migrate. It does probably add a ton of complexity to the codebase though, and seeing as XMR fees are dirt cheap, it doesn't seem like a worthwhile endeavor when a user can just cheaply move zaps they get to their other wallets if they like.

While Garnet does have a Monero wallet built in, it's primary function is not to be a Monero wallet, it is to be a Nostr client with Monero tipping functionality. Adding in functionality that makes it work like a generic Monero wallet seems to be out of scope.

As far as I understand it, Garnet is designed to be able to parse an XMR address from your profile if you already have one instead of generating a new one from your nsec, although it appears that that functionality isn't working correctly right now (this is easy, but not trivial, to do and there will always be formatting problems with it), so it basically already gives you the ability to use any seed you want to receive zaps, you just aren't able to use the built in wallet to send or view your coins and transaction history.

**Comment by retrnull** [comment]
As mister-monster says, the app is intended to be used with a spend key derived from your Nostr private key. Allowing arbitrary Monero wallets to be used in the app is not the intended functionality.

**Comment by retrnull** [comment]
@mister-monster parsing XMR addresses from the profile should work correctly in v0.3.0 (as long as it is separated from the other strings by some kind of white space). Please open an issue if it still doesn't work correctly.
